import { ComponentDefinition } from '../types';

export const COMPONENTS: ComponentDefinition[] = [
  // ─── Frontend ──────────────────────────────────────────────────────────────
  {
    id: 'web-app',
    name: 'Web App',
    category: 'frontend',
    icon: 'Globe',
    description: 'Browser-based web application',
    defaultStyle: { color: '#fff', background: '#6366f1', border: '#4f46e5', borderRadius: 12, shadow: true },
  },
  {
    id: 'mobile-app',
    name: 'Mobile App',
    category: 'frontend',
    icon: 'Smartphone',
    description: 'iOS / Android mobile application',
    defaultStyle: { color: '#fff', background: '#8b5cf6', border: '#7c3aed', borderRadius: 12, shadow: true },
  },
  {
    id: 'desktop-app',
    name: 'Desktop App',
    category: 'frontend',
    icon: 'Monitor',
    description: 'Cross-platform desktop application',
    defaultStyle: { color: '#fff', background: '#7c3aed', border: '#6d28d9', borderRadius: 12, shadow: true },
  },

  // ─── Backend ───────────────────────────────────────────────────────────────
  {
    id: 'rest-api',
    name: 'REST API',
    category: 'backend',
    icon: 'Network',
    description: 'RESTful HTTP API service',
    defaultStyle: { color: '#fff', background: '#0ea5e9', border: '#0284c7', borderRadius: 12, shadow: true },
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    category: 'backend',
    icon: 'GitMerge',
    description: 'GraphQL API server',
    defaultStyle: { color: '#fff', background: '#e11d9b', border: '#c21b85', borderRadius: 12, shadow: true },
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'backend',
    icon: 'Server',
    description: 'Node.js runtime server',
    defaultStyle: { color: '#fff', background: '#22c55e', border: '#16a34a', borderRadius: 12, shadow: true },
  },
  {
    id: 'express',
    name: 'Express',
    category: 'backend',
    icon: 'Zap',
    description: 'Express.js web framework',
    defaultStyle: { color: '#fff', background: '#374151', border: '#1f2937', borderRadius: 12, shadow: true },
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'backend',
    icon: 'Triangle',
    description: 'Next.js full-stack framework',
    defaultStyle: { color: '#fff', background: '#171717', border: '#000', borderRadius: 12, shadow: true },
  },

  // ─── Database ──────────────────────────────────────────────────────────────
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    icon: 'Database',
    description: 'PostgreSQL relational database',
    defaultStyle: { color: '#fff', background: '#336791', border: '#2a5475', borderRadius: 12, shadow: true },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'database',
    icon: 'Leaf',
    description: 'MongoDB document database',
    defaultStyle: { color: '#fff', background: '#4db33d', border: '#3d9030', borderRadius: 12, shadow: true },
  },
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'database',
    icon: 'Database',
    description: 'MySQL relational database',
    defaultStyle: { color: '#fff', background: '#00758f', border: '#005f76', borderRadius: 12, shadow: true },
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'database',
    icon: 'Layers',
    description: 'Redis in-memory data store',
    defaultStyle: { color: '#fff', background: '#d82c20', border: '#b52319', borderRadius: 12, shadow: true },
  },
  {
    id: 'elasticsearch',
    name: 'ElasticSearch',
    category: 'database',
    icon: 'Search',
    description: 'Elasticsearch search engine',
    defaultStyle: { color: '#fff', background: '#f5a623', border: '#d4891a', borderRadius: 12, shadow: true },
  },

  // ─── Queue / Messaging ─────────────────────────────────────────────────────
  {
    id: 'kafka',
    name: 'Kafka',
    category: 'queue',
    icon: 'Activity',
    description: 'Apache Kafka event streaming',
    defaultStyle: { color: '#fff', background: '#231f20', border: '#000', borderRadius: 12, shadow: true },
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    category: 'queue',
    icon: 'MessageSquare',
    description: 'RabbitMQ message broker',
    defaultStyle: { color: '#fff', background: '#ff6600', border: '#cc5200', borderRadius: 12, shadow: true },
  },
  {
    id: 'event-bus',
    name: 'Event Bus',
    category: 'messaging',
    icon: 'Radio',
    description: 'Internal event bus / pub-sub',
    defaultStyle: { color: '#fff', background: '#7c3aed', border: '#6d28d9', borderRadius: 12, shadow: true },
  },

  // ─── Infrastructure ────────────────────────────────────────────────────────
  {
    id: 'nginx',
    name: 'Nginx',
    category: 'infrastructure',
    icon: 'Shield',
    description: 'Nginx web server / reverse proxy',
    defaultStyle: { color: '#fff', background: '#009639', border: '#007a2e', borderRadius: 12, shadow: true },
  },
  {
    id: 'load-balancer',
    name: 'Load Balancer',
    category: 'infrastructure',
    icon: 'BarChart2',
    description: 'Traffic load balancer',
    defaultStyle: { color: '#fff', background: '#f59e0b', border: '#d97706', borderRadius: 12, shadow: true },
  },
  {
    id: 'api-gateway',
    name: 'API Gateway',
    category: 'api',
    icon: 'GitFork',
    description: 'API gateway for routing and auth',
    defaultStyle: { color: '#fff', background: '#ef4444', border: '#dc2626', borderRadius: 12, shadow: true },
  },

  // ─── Deployment ────────────────────────────────────────────────────────────
  {
    id: 'docker',
    name: 'Docker',
    category: 'deployment',
    icon: 'Box',
    description: 'Docker container',
    defaultStyle: { color: '#fff', background: '#2496ed', border: '#1a78c4', borderRadius: 12, shadow: true },
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'deployment',
    icon: 'Hexagon',
    description: 'Kubernetes orchestration',
    defaultStyle: { color: '#fff', background: '#326ce5', border: '#2857c5', borderRadius: 12, shadow: true },
  },
  {
    id: 'cdn',
    name: 'CDN',
    category: 'cloud',
    icon: 'Globe2',
    description: 'Content delivery network',
    defaultStyle: { color: '#fff', background: '#f97316', border: '#ea580c', borderRadius: 12, shadow: true },
  },

  // ─── Storage ───────────────────────────────────────────────────────────────
  {
    id: 's3',
    name: 'S3',
    category: 'storage',
    icon: 'HardDrive',
    description: 'Amazon S3 object storage',
    defaultStyle: { color: '#fff', background: '#e8a117', border: '#c78a13', borderRadius: 12, shadow: true },
  },
  {
    id: 'firebase',
    name: 'Firebase',
    category: 'storage',
    icon: 'Flame',
    description: 'Google Firebase platform',
    defaultStyle: { color: '#fff', background: '#ff9800', border: '#e68900', borderRadius: 12, shadow: true },
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'storage',
    icon: 'Database',
    description: 'Supabase open-source Firebase alternative',
    defaultStyle: { color: '#fff', background: '#3ecf8e', border: '#2eaf74', borderRadius: 12, shadow: true },
  },

  // ─── Authentication ────────────────────────────────────────────────────────
  {
    id: 'oauth',
    name: 'OAuth',
    category: 'authentication',
    icon: 'Key',
    description: 'OAuth 2.0 authentication provider',
    defaultStyle: { color: '#fff', background: '#10b981', border: '#059669', borderRadius: 12, shadow: true },
  },
  {
    id: 'jwt',
    name: 'JWT',
    category: 'authentication',
    icon: 'Lock',
    description: 'JSON Web Token authentication',
    defaultStyle: { color: '#fff', background: '#f43f5e', border: '#e11d48', borderRadius: 12, shadow: true },
  },
  {
    id: 'email-service',
    name: 'Email',
    category: 'authentication',
    icon: 'Mail',
    description: 'Email service (SendGrid, SES)',
    defaultStyle: { color: '#fff', background: '#6366f1', border: '#4f46e5', borderRadius: 12, shadow: true },
  },

  // ─── Cloud & Serverless ────────────────────────────────────────────────────
  {
    id: 'lambda',
    name: 'Lambda',
    category: 'cloud',
    icon: 'Cpu',
    description: 'AWS Lambda serverless function',
    defaultStyle: { color: '#fff', background: '#ff9900', border: '#e68900', borderRadius: 12, shadow: true },
  },
  {
    id: 'cloud-function',
    name: 'Cloud Function',
    category: 'cloud',
    icon: 'Cloud',
    description: 'Google Cloud / Azure function',
    defaultStyle: { color: '#fff', background: '#4285f4', border: '#3367d6', borderRadius: 12, shadow: true },
  },
  {
    id: 'serverless',
    name: 'Serverless',
    category: 'cloud',
    icon: 'Wind',
    description: 'Serverless compute layer',
    defaultStyle: { color: '#fff', background: '#fd5750', border: '#e34c46', borderRadius: 12, shadow: true },
  },

  // ─── Monitoring ────────────────────────────────────────────────────────────
  {
    id: 'monitoring',
    name: 'Monitoring',
    category: 'monitoring',
    icon: 'Activity',
    description: 'System monitoring (Datadog, Grafana)',
    defaultStyle: { color: '#fff', background: '#632ca6', border: '#4f2284', borderRadius: 12, shadow: true },
  },
  {
    id: 'logging',
    name: 'Logging',
    category: 'monitoring',
    icon: 'FileText',
    description: 'Centralized logging (ELK, Splunk)',
    defaultStyle: { color: '#fff', background: '#0d9488', border: '#0b7d74', borderRadius: 12, shadow: true },
  },
  {
    id: 'analytics',
    name: 'Analytics',
    category: 'monitoring',
    icon: 'TrendingUp',
    description: 'Analytics platform',
    defaultStyle: { color: '#fff', background: '#3b82f6', border: '#2563eb', borderRadius: 12, shadow: true },
  },

  // ─── Utilities ────────────────────────────────────────────────────────────
  {
    id: 'payment',
    name: 'Payment',
    category: 'utilities',
    icon: 'CreditCard',
    description: 'Payment gateway (Stripe, PayPal)',
    defaultStyle: { color: '#fff', background: '#635bff', border: '#4d47e0', borderRadius: 12, shadow: true },
  },
  {
    id: 'notification',
    name: 'Notification',
    category: 'utilities',
    icon: 'Bell',
    description: 'Push notification service',
    defaultStyle: { color: '#fff', background: '#f59e0b', border: '#d97706', borderRadius: 12, shadow: true },
  },
  {
    id: 'worker',
    name: 'Worker',
    category: 'utilities',
    icon: 'Settings',
    description: 'Background worker process',
    defaultStyle: { color: '#fff', background: '#64748b', border: '#475569', borderRadius: 12, shadow: true },
  },
  {
    id: 'cron',
    name: 'Cron',
    category: 'utilities',
    icon: 'Clock',
    description: 'Scheduled cron job',
    defaultStyle: { color: '#fff', background: '#78716c', border: '#57534e', borderRadius: 12, shadow: true },
  },
  {
    id: 'cache',
    name: 'Cache',
    category: 'utilities',
    icon: 'Layers',
    description: 'Caching layer',
    defaultStyle: { color: '#fff', background: '#0891b2', border: '#0e7490', borderRadius: 12, shadow: true },
  },
  {
    id: 'microservice',
    name: 'Microservice',
    category: 'backend',
    icon: 'Package',
    description: 'Independent microservice',
    defaultStyle: { color: '#fff', background: '#7e22ce', border: '#6b21a8', borderRadius: 12, shadow: true },
  },
  {
    id: 'proxy',
    name: 'Proxy',
    category: 'networking',
    icon: 'ArrowLeftRight',
    description: 'Network proxy server',
    defaultStyle: { color: '#fff', background: '#374151', border: '#1f2937', borderRadius: 12, shadow: true },
  },
  {
    id: 'dns',
    name: 'DNS',
    category: 'networking',
    icon: 'Globe',
    description: 'Domain name system',
    defaultStyle: { color: '#fff', background: '#0369a1', border: '#075985', borderRadius: 12, shadow: true },
  },
  {
    id: 'webhook',
    name: 'Webhook',
    category: 'utilities',
    icon: 'Webhook',
    description: 'HTTP callback webhook',
    defaultStyle: { color: '#fff', background: '#c026d3', border: '#a21caf', borderRadius: 12, shadow: true },
  },
  {
    id: 'socket',
    name: 'WebSocket',
    category: 'utilities',
    icon: 'Wifi',
    description: 'WebSocket real-time connection',
    defaultStyle: { color: '#fff', background: '#059669', border: '#047857', borderRadius: 12, shadow: true },
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  frontend: 'Frontend',
  backend: 'Backend',
  api: 'API',
  authentication: 'Authentication',
  database: 'Database',
  storage: 'Storage',
  cloud: 'Cloud',
  queue: 'Queue',
  messaging: 'Messaging',
  infrastructure: 'Infrastructure',
  monitoring: 'Monitoring',
  security: 'Security',
  networking: 'Networking',
  deployment: 'Deployment',
  utilities: 'Utilities',
};

export const CATEGORY_COLORS: Record<string, string> = {
  frontend: '#6366f1',
  backend: '#0ea5e9',
  api: '#ef4444',
  authentication: '#10b981',
  database: '#336791',
  storage: '#f59e0b',
  cloud: '#f97316',
  queue: '#ff6600',
  messaging: '#7c3aed',
  infrastructure: '#22c55e',
  monitoring: '#632ca6',
  security: '#dc2626',
  networking: '#0369a1',
  deployment: '#2496ed',
  utilities: '#64748b',
};
